FROM nvcr.io/nvidia/pytorch:23.06-py3

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y libpgm-dev net-tools

WORKDIR /
COPY ./zeromq-4.3.4.tar.gz /
RUN tar zxvf /zeromq-4.3.4.tar.gz
WORKDIR /zeromq-4.3.4
RUN ./configure --with-pgm && make && make install

RUN pip3 install -U pip
RUN pip3 install -I --no-binary=:all: pyzmq
RUN pip3 install -U cmake prometheus_client wandb redis scipy \
	Deprecated einops kornia pybind11 icetk h5py ninja packaging
RUN pip3 install -U transformers huggingface_hub
RUN pip3 install -U deepspeed
RUN pip3 install -U triton
RUN pip3 install -U flash-attn --no-build-isolation
# RUN pip3 install -U vllm
RUN pip3 install -U ray

WORKDIR /

#RUN pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
