ARG base_image=nvcr.io/nvidia/pytorch:23.06-py3

FROM ${base_image}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y ca-certificates
RUN sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN apt update
RUN apt install -y libpgm-dev net-tools python3-opencv ffmpeg libsm6 libxext6 python3-pip pkg-config libopenblas-base libopenmpi-dev

COPY ./zeromq-4.3.4.tar.gz /
WORKDIR /
RUN tar zxvf zeromq-4.3.4.tar.gz
WORKDIR /zeromq-4.3.4
RUN ./configure --with-pgm && make && make install
WORKDIR /

RUN pip3 install -U pip
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install -I --no-binary=:all: pyzmq

RUN pip3 install -U torch torchvision torchaudio

RUN pip3 install -U blosc cmake prometheus_client wandb redis scipy \
	Deprecated einops kornia pybind11 icetk h5py ninja packaging "protobuf<=3.20.x"
RUN pip3 install -U transformers huggingface_hub datasets accelerate bitsandbytes
RUN pip3 install -U deepspeed
RUN pip3 install -U triton
RUN pip3 install -U "flash-attn<2" --no-build-isolation
RUN pip3 install -U ray[default,serve,data]
RUN pip3 install "protobuf<=3.20.x"

# RUN pip3 install -U vllm