ARG base_image

FROM ${base_image}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y ca-certificates
RUN sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN apt update
RUN apt install -y libpgm-dev net-tools python3-opencv ffmpeg libsm6 libxext6 python3-pip pkg-config libopenblas-base libopenmpi-dev

RUN pip3 install -U pip
# RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install -U ray[default,serve,data] -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install -U transformers huggingface_hub datasets accelerate bitsandbytes -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install -U deepspeed -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip3 install -U blosc cmake prometheus_client wandb redis scipy h5py ninja packaging tensorboardx sentencepiece numba viztracer[full] pyzmq -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install colorlog colorama -i https://pypi.tuna.tsinghua.edu.cn/simple

